## Write a Numpy program to compute the multiplication of two given matrixes

In [ ]:
#Write a NumPy program to compute the multiplication of two given matrixes.

Sample Matrix:

#[[3, 4], [2, 1]]
#[[1, 2], [3, 4]]

In [3]:
import numpy as np
p = [[3, 4], [2, 1]]
q = [[1, 2], [3, 4]]
print("original matrix:")
print(p)
print(q)
result1 = np.dot(p, q)
print("Result of the said matrix multiplication:")
print(result1)

original matrix:
[[3, 4], [2, 1]]
[[1, 2], [3, 4]]
Result of the said matrix multiplication:
[[15 22]
 [ 5  8]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
# Importing libraries
import numpy as np
from numpy import linalg
  
# Creating a 2X2 matrix
matrix = np.array([[7, 8], [4, 5]])
print("Original 2-D matrix")
print(matrix)
  
# Output
print("Determinant of the 2-D matrix:")
print(np.linalg.det(matrix))

Original 2-D matrix
[[7 8]
 [4 5]]
Determinant of the 2-D matrix:
3.0000000000000018


## Write a NumPy program to compute the cross product of two given vectors

In [7]:
# import library
import numpy as np
  
# declare vectors
x = [[1, 2], [3, 3]]
y = [[5, 5], [7, 9]]
  
# find cross product of
# two given vectors
result = np.cross(x, y)
  
# show the result
print(result)

[-5  6]


## Write a NumPy program to compute the condition number of a given matrix

In [9]:
import numpy as np
m = np.array([[4,2],[3,4]])
print("Original matrix:")
print(m)
result =  np.linalg.cond(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[4 2]
 [3 4]]
Condition number of the said matrix:
4.265564437074637


## Write a NumPy program to compute the inverse of a given matrix

In [13]:
# Python program to inverse
# a matrix using numpy

# Import required package
import numpy as np

# Taking a 3 * 3 matrix
i= np.array([[6, 1, 1],
[4, 3, 5],
[-1, 8, 7]])

# Calculating the inverse of the matrix
print(np.linalg.inv(i))


[[ 0.16964286 -0.00892857 -0.01785714]
 [ 0.29464286 -0.38392857  0.23214286]
 [-0.3125      0.4375     -0.125     ]]
