In [3]:
#Write a Numpy program to compute the multiplication of two given matrixes
import numpy as np


array([[ 32,  43,  49],
       [ 74, 109, 121],
       [116, 175, 193]])

In [5]:
m=[[1,2,3],[4,5,6],[7,8,9]]
m0=[[1,8,7],[8,7,9],[5,7,8]]
m1=np.array(m)
m2=np.array(m0)


In [6]:
m_mul=np.dot(m1,m2)
m_mul



array([[ 32,  43,  49],
       [ 74, 109, 121],
       [116, 175, 193]])

In [7]:

#Write a NumPy program to compute the determinant of a given square array
m3=np.square(m1)
m3



array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [9]:
#Write a NumPy program to compute the cross product of two given vectors
m_0=[1,3]
m_1=[1,4]


In [10]:
m4=np.cross(m_0,m_1)
m4


array(1)

In [11]:
#Write a NumPy program to compute the condition number of a given matrix
m5=np.linalg.cond(m1)
m5


3.813147060626918e+16

In [12]:

#Write a NumPy program to compute the inverse of a given matrix
m6=np.linalg.inv(m2)
m6


array([[ 0.58333333,  1.25      , -1.91666667],
       [ 1.58333333,  2.25      , -3.91666667],
       [-1.75      , -2.75      ,  4.75      ]])